# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# see: https://help.github.com/articles/page-build-failed-relative-permalinks-configured/
# relative_permalinks: true

# Setup
title:               SPV
tagline:             "Welcome"
description:         "Make a difference"
url:                 http://spv.me
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Siva Prasad Varma
  url:               https://twitter.com/sivapvarma
  email:             sivapvarma@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
