# permalink
permalink:           pretty

# Setup
title:               SPV
tagline:             "Welcome"
description:         "Make a difference"
url:                 http://spv.me
paginate:            5

# About/contact
author:
  name:              Siva Prasad Varma
  url:               https://twitter.com/sivapvarma
  email:             sivapvarma@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
