# permalink
permalink:           pretty

# Setup
title:               SPV
tagline:             "Welcome"
description:         "My biased coin"
url:                 http://spv.me
timezone:            America/Los_Angeles

# Pagination
paginate:            5

# About/contact
author:
  name:              "Siva Prasad Varma"
  url:               https://twitter.com/sivapvarma
  email:             sivapvarma@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-last-modified-at

collections:
  notes:
    output: true
  teaching:
    output: true